export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SAVE_FIREBASE_INSTANCE = 'SAVE_FIREBASE_INSTANCE';
export const SAVE_CURRENT_USER = 'SAVE_CURRENT_USER';
export const SAVE_AUTH_PROFILE = 'SAVE_AUTH_PROFILE';
export const UPDATE_CURRENT_USER_PROFILE = 'UPDATE_CURRENT_USER_PROFILE';

